language: python
python:
  - "3.7"

# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install .
# command to run tests
script:
  - pytest # or py.test for Python versions 3.5 and below